repo_url: https://github.com/Interacao-Humano-Computador/2023.2-Grupo01
repo_name: 2023.1-Grupo01

site_name: Nota Legal
nav:
  - Home: index.md
  - Atas:
    - Reunião 1: atas/Reuniao01-31.08.2023.md
    - Reunião 2: atas/Reuniao02-05.09.2023.md
    - Reunião 3: atas/Reuniao03-13.09.2023.md
    - Reunião 4: atas/Reuniao04-20.09.2023.md
    - Reunião 5: atas/Reuniao05-22.09.2023.md
    - Reunião 6: atas/Reuniao06-04.10.2023.md
    - Reunião 7: atas/Reuniao07-06.10.2023.md
    - Reunião 8: atas/Reuniao08-11.10.2023.md
  - Apresentações:
    - Apresentação 1: apresentacoes/Apresentação 1 - 29.09.2023.md
    - Apresentação 2: apresentacoes/Apresentação 2 - 13.10.2023.md
  - Planejamento do Projeto:
    - Heatmap de disponibilidade: planejamento do projeto/heatmap-disponibilidade.md
    - Sites avaliados: planejamento do projeto/lista-sites-avaliados.md
    - Site escolhido: planejamento do projeto/site-escolhido.md
    - Ferramentas: planejamento do projeto/ferramentas.md
    - Processo de Design: planejamento do projeto/processo-de-design.md
    - Cronograma planejado: planejamento do projeto/cronograma_planejado.md
    - Cronograma executado: planejamento do projeto/cronograma_executado.md
  - Análise de Requisitos:
    - Aspectos éticos: analise de requisitos/aspectos-eticos.md
    - Perfil do usuário: 
      - Termo de Consentimento Livre e Esclarecido: analise de requisitos/tecnicas-perfil-usuario/termo_de_consentimento_perfilUsuario.md
      - Grupo de foco: analise de requisitos/tecnicas-perfil-usuario/grupo_de_foco.md
      - Questionário: analise de requisitos/tecnicas-perfil-usuario/questionario.md
      - Perfil do Usuário: analise de requisitos/perfil_usuario.md
    - Personas: analise de requisitos/personas.md
    - Cenários: analise de requisitos/cenarios.md
    - Análise de Tarefas:
      - Análise Hierárquica de Tarefas (HTA): analise de requisitos/tecnicas-analise-de-tarefas/hta.md
      - Árvore de Tarefas Concorrentes (CTT): analise de requisitos/tecnicas-analise-de-tarefas/ctt.md
    - Requisitos do Usuário:
      - Brainstorming: analise de requisitos/tecnicas-elicitacao/brainstorming.md
      - Instrospecção: analise de requisitos/tecnicas-elicitacao/instrospeccao.md
      - Observação: analise de requisitos/tecnicas-elicitacao/observacao.md
      - Requisitos elicitados: analise de requisitos/requisitos-elicitados.md
    
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - primary: green
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
